#!/bin/bash
# test_plan.sh
# Run this script, or use it as a guide for your Demo Vivo session.

echo "============================================="
echo " SDN Link Failure Detection & Recovery Demo  "
echo "============================================="
echo ""
echo "Please perform these steps in your Ubuntu 22.xx environment:"
echo ""
echo "--- Preparation (Terminal 1) ---"
echo "If you don't have POX installed, clone it:"
echo "$ git clone https://github.com/noxrepo/pox.git ~/pox"
echo ""
echo "Copy the controller script to POX's ext folder:"
echo "$ cp controller.py ~/pox/ext/"
echo ""
echo "--- Terminal 1: Run Controller ---"
echo "$ cd ~/pox"
echo "$ ./pox.py log.level --INFO controller"
echo "  Note: Wait a few seconds for the controller to initialize STP (spanning tree protocol)"
echo ""
echo "--- Terminal 2: Run Mininet ---"
echo "$ sudo python3 topology.py"
echo ""
echo "--- Once Mininet CLI 'mininet>' appears: ---"
echo ""
echo "Step 1: Test basic connectivity and populate MAC tables"
echo "mininet> pingall"
echo "mininet> h1 ping h2"
echo "  (Let ping run or use 'h1 ping -c 10 h2')"
echo ""
echo "Step 2: Start an Iperf server on H2 and client on H1 (Optional)"
echo "mininet> h2 iperf -s &"
echo "mininet> h1 iperf -c h2"
echo ""
echo "Step 3: Simulate Link Failure"
echo "By default, traffic between H1 and H2 might take S1 <-> S3."
echo "Let's bring that direct link down while ping is running in another terminal window."
echo "mininet> link s1 s3 down"
echo ""
echo "Observe the Controller console (Terminal 1)."
echo "You will see: 'Link DOWN detected... Cleared OpenFlow rules...'"
echo ""
echo "Step 4: Verify Connectivity Restoration"
echo "Notice that ping temporarily fails, but then successfully resumes as "
echo "traffic is routed via the backup path (S1 <-> S2 <-> S3)."
echo ""
echo "Step 5: Verify Link Restore (Optional)"
echo "Bring the link back up to see it transition back:"
echo "mininet> link s1 s3 up"
echo ""
echo "Step 6: Clean up"
echo "mininet> exit"
echo "$ sudo mn -c"
echo ""
echo "============================================="
